/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppArticulosIndexRouteImport } from './routes/_app.articulos.index'
import { Route as AppAlbaranesVentaIndexRouteImport } from './routes/_app.albaranes-venta.index'
import { Route as AppAlbaranesCompraIndexRouteImport } from './routes/_app.albaranes-compra.index'
import { Route as AppConfiguracionImportarRouteImport } from './routes/_app.configuracion.importar'
import { Route as AppArticulosIdRouteImport } from './routes/_app.articulos.$id'
import { Route as AppAlbaranesVentaNuevoRouteImport } from './routes/_app.albaranes-venta.nuevo'
import { Route as AppAlbaranesVentaIdRouteImport } from './routes/_app.albaranes-venta.$id'
import { Route as AppAlbaranesCompraNuevoRouteImport } from './routes/_app.albaranes-compra.nuevo'
import { Route as AppAlbaranesCompraIdRouteImport } from './routes/_app.albaranes-compra.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppArticulosIndexRoute = AppArticulosIndexRouteImport.update({
  id: '/articulos/',
  path: '/articulos/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlbaranesVentaIndexRoute = AppAlbaranesVentaIndexRouteImport.update({
  id: '/albaranes-venta/',
  path: '/albaranes-venta/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlbaranesCompraIndexRoute = AppAlbaranesCompraIndexRouteImport.update({
  id: '/albaranes-compra/',
  path: '/albaranes-compra/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionImportarRoute =
  AppConfiguracionImportarRouteImport.update({
    id: '/configuracion/importar',
    path: '/configuracion/importar',
    getParentRoute: () => AppRoute,
  } as any)
const AppArticulosIdRoute = AppArticulosIdRouteImport.update({
  id: '/articulos/$id',
  path: '/articulos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAlbaranesVentaNuevoRoute = AppAlbaranesVentaNuevoRouteImport.update({
  id: '/albaranes-venta/nuevo',
  path: '/albaranes-venta/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppAlbaranesVentaIdRoute = AppAlbaranesVentaIdRouteImport.update({
  id: '/albaranes-venta/$id',
  path: '/albaranes-venta/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAlbaranesCompraNuevoRoute = AppAlbaranesCompraNuevoRouteImport.update({
  id: '/albaranes-compra/nuevo',
  path: '/albaranes-compra/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppAlbaranesCompraIdRoute = AppAlbaranesCompraIdRouteImport.update({
  id: '/albaranes-compra/$id',
  path: '/albaranes-compra/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/albaranes-compra/$id': typeof AppAlbaranesCompraIdRoute
  '/albaranes-compra/nuevo': typeof AppAlbaranesCompraNuevoRoute
  '/albaranes-venta/$id': typeof AppAlbaranesVentaIdRoute
  '/albaranes-venta/nuevo': typeof AppAlbaranesVentaNuevoRoute
  '/articulos/$id': typeof AppArticulosIdRoute
  '/configuracion/importar': typeof AppConfiguracionImportarRoute
  '/albaranes-compra/': typeof AppAlbaranesCompraIndexRoute
  '/albaranes-venta/': typeof AppAlbaranesVentaIndexRoute
  '/articulos/': typeof AppArticulosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/albaranes-compra/$id': typeof AppAlbaranesCompraIdRoute
  '/albaranes-compra/nuevo': typeof AppAlbaranesCompraNuevoRoute
  '/albaranes-venta/$id': typeof AppAlbaranesVentaIdRoute
  '/albaranes-venta/nuevo': typeof AppAlbaranesVentaNuevoRoute
  '/articulos/$id': typeof AppArticulosIdRoute
  '/configuracion/importar': typeof AppConfiguracionImportarRoute
  '/albaranes-compra': typeof AppAlbaranesCompraIndexRoute
  '/albaranes-venta': typeof AppAlbaranesVentaIndexRoute
  '/articulos': typeof AppArticulosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/albaranes-compra/$id': typeof AppAlbaranesCompraIdRoute
  '/_app/albaranes-compra/nuevo': typeof AppAlbaranesCompraNuevoRoute
  '/_app/albaranes-venta/$id': typeof AppAlbaranesVentaIdRoute
  '/_app/albaranes-venta/nuevo': typeof AppAlbaranesVentaNuevoRoute
  '/_app/articulos/$id': typeof AppArticulosIdRoute
  '/_app/configuracion/importar': typeof AppConfiguracionImportarRoute
  '/_app/albaranes-compra/': typeof AppAlbaranesCompraIndexRoute
  '/_app/albaranes-venta/': typeof AppAlbaranesVentaIndexRoute
  '/_app/articulos/': typeof AppArticulosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/albaranes-compra/$id'
    | '/albaranes-compra/nuevo'
    | '/albaranes-venta/$id'
    | '/albaranes-venta/nuevo'
    | '/articulos/$id'
    | '/configuracion/importar'
    | '/albaranes-compra/'
    | '/albaranes-venta/'
    | '/articulos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/albaranes-compra/$id'
    | '/albaranes-compra/nuevo'
    | '/albaranes-venta/$id'
    | '/albaranes-venta/nuevo'
    | '/articulos/$id'
    | '/configuracion/importar'
    | '/albaranes-compra'
    | '/albaranes-venta'
    | '/articulos'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/albaranes-compra/$id'
    | '/_app/albaranes-compra/nuevo'
    | '/_app/albaranes-venta/$id'
    | '/_app/albaranes-venta/nuevo'
    | '/_app/articulos/$id'
    | '/_app/configuracion/importar'
    | '/_app/albaranes-compra/'
    | '/_app/albaranes-venta/'
    | '/_app/articulos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articulos/': {
      id: '/_app/articulos/'
      path: '/articulos'
      fullPath: '/articulos/'
      preLoaderRoute: typeof AppArticulosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/albaranes-venta/': {
      id: '/_app/albaranes-venta/'
      path: '/albaranes-venta'
      fullPath: '/albaranes-venta/'
      preLoaderRoute: typeof AppAlbaranesVentaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/albaranes-compra/': {
      id: '/_app/albaranes-compra/'
      path: '/albaranes-compra'
      fullPath: '/albaranes-compra/'
      preLoaderRoute: typeof AppAlbaranesCompraIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion/importar': {
      id: '/_app/configuracion/importar'
      path: '/configuracion/importar'
      fullPath: '/configuracion/importar'
      preLoaderRoute: typeof AppConfiguracionImportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articulos/$id': {
      id: '/_app/articulos/$id'
      path: '/articulos/$id'
      fullPath: '/articulos/$id'
      preLoaderRoute: typeof AppArticulosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/albaranes-venta/nuevo': {
      id: '/_app/albaranes-venta/nuevo'
      path: '/albaranes-venta/nuevo'
      fullPath: '/albaranes-venta/nuevo'
      preLoaderRoute: typeof AppAlbaranesVentaNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/albaranes-venta/$id': {
      id: '/_app/albaranes-venta/$id'
      path: '/albaranes-venta/$id'
      fullPath: '/albaranes-venta/$id'
      preLoaderRoute: typeof AppAlbaranesVentaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/albaranes-compra/nuevo': {
      id: '/_app/albaranes-compra/nuevo'
      path: '/albaranes-compra/nuevo'
      fullPath: '/albaranes-compra/nuevo'
      preLoaderRoute: typeof AppAlbaranesCompraNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/albaranes-compra/$id': {
      id: '/_app/albaranes-compra/$id'
      path: '/albaranes-compra/$id'
      fullPath: '/albaranes-compra/$id'
      preLoaderRoute: typeof AppAlbaranesCompraIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAlbaranesCompraIdRoute: typeof AppAlbaranesCompraIdRoute
  AppAlbaranesCompraNuevoRoute: typeof AppAlbaranesCompraNuevoRoute
  AppAlbaranesVentaIdRoute: typeof AppAlbaranesVentaIdRoute
  AppAlbaranesVentaNuevoRoute: typeof AppAlbaranesVentaNuevoRoute
  AppArticulosIdRoute: typeof AppArticulosIdRoute
  AppConfiguracionImportarRoute: typeof AppConfiguracionImportarRoute
  AppAlbaranesCompraIndexRoute: typeof AppAlbaranesCompraIndexRoute
  AppAlbaranesVentaIndexRoute: typeof AppAlbaranesVentaIndexRoute
  AppArticulosIndexRoute: typeof AppArticulosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAlbaranesCompraIdRoute: AppAlbaranesCompraIdRoute,
  AppAlbaranesCompraNuevoRoute: AppAlbaranesCompraNuevoRoute,
  AppAlbaranesVentaIdRoute: AppAlbaranesVentaIdRoute,
  AppAlbaranesVentaNuevoRoute: AppAlbaranesVentaNuevoRoute,
  AppArticulosIdRoute: AppArticulosIdRoute,
  AppConfiguracionImportarRoute: AppConfiguracionImportarRoute,
  AppAlbaranesCompraIndexRoute: AppAlbaranesCompraIndexRoute,
  AppAlbaranesVentaIndexRoute: AppAlbaranesVentaIndexRoute,
  AppArticulosIndexRoute: AppArticulosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
